version: 0.2

phases:

  build:
    commands:
      - ./mvnw package
      - echo Jar file built successfully.
      - echo "S3 bucket is $S3_BUCKET"
      - echo "S3 bucket is $JAR_FILE_NAME"
      - aws s3 cp target/quarkus-app/quarkus-run.jar "s3://$S3_BUCKET/$JAR_FILE_NAME"
      - aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters '{"commands":["chmod +x /home/ec2-user/deploy.sh","/home/ec2-user/deploy.sh"],"executionTimeout":["3600"]}' --comment "Running deploy.sh script on EC2 instance" --timeout-seconds 600