version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 800210167969.dkr.ecr.ap-south-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw package
      - docker build --platform linux/amd64 -f src/main/docker/Dockerfile.jvm -t quarkus/integration-jvm .
      - docker tag quarkus/integration-jvm:latest 800210167969.dkr.ecr.ap-south-1.amazonaws.com/marketplace-plugins:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 800210167969.dkr.ecr.ap-south-1.amazonaws.com/marketplace-plugins:latest
      
artifacts:
  files:
    - target/**/*
    - src/**/*
    - pom.xml
    - buildspec.yaml